package view;

import model.Tarefa;
import repository.TarefaRepository;
import javax.swing.JOptionPane;

public class JanelaNovaTarefa extends javax.swing.JFrame {

    private static JanelaNovaTarefa instancia;
    private JanelaPrincipal janelaPrincipal;

    /**
     * Creates new form JanelaNovaTarefa
     */
    public JanelaNovaTarefa(JanelaPrincipal janelaPrincipal) {
        initComponents();
        this.janelaPrincipal = janelaPrincipal;
        //txtId.setVisible(false); //escondendo txtId
        txtId.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        newTaskWindow = new javax.swing.JInternalFrame();
        taskName = new javax.swing.JLabel();
        taskName1 = new javax.swing.JLabel();
        taskName2 = new javax.swing.JLabel();
        taskName3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtNomeDaTarefa = new javax.swing.JTextField();
        txtDataDeCriacao = new javax.swing.JTextField();
        btnRetroceder = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnIrParaMenu = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        checkBoxConcluido = new javax.swing.JCheckBox();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setTitle("Nova Tarefa");

        newTaskWindow.setTitle("Nova Tarefa");
        newTaskWindow.setVisible(true);

        taskName.setText("Nome da Tarefa:");

        taskName1.setText("Descrição:");

        taskName2.setText("Data de Criação:");

        taskName3.setText("Concluída:");

        btnRetroceder.setText("«");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        btnAvancar.setText("»");

        btnIrParaMenu.setText("Menu");
        btnIrParaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrParaMenuActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        checkBoxConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxConcluidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newTaskWindowLayout = new javax.swing.GroupLayout(newTaskWindow.getContentPane());
        newTaskWindow.getContentPane().setLayout(newTaskWindowLayout);
        newTaskWindowLayout.setHorizontalGroup(
            newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newTaskWindowLayout.createSequentialGroup()
                .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newTaskWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newTaskWindowLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newTaskWindowLayout.createSequentialGroup()
                                .addComponent(taskName3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkBoxConcluido))
                            .addGroup(newTaskWindowLayout.createSequentialGroup()
                                .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(newTaskWindowLayout.createSequentialGroup()
                                        .addComponent(taskName2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDataDeCriacao))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newTaskWindowLayout.createSequentialGroup()
                                        .addComponent(taskName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNomeDaTarefa))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newTaskWindowLayout.createSequentialGroup()
                                        .addComponent(taskName1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newTaskWindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIrParaMenu)
                        .addGap(14, 14, 14))))
        );
        newTaskWindowLayout.setVerticalGroup(
            newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newTaskWindowLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskName)
                    .addComponent(txtNomeDaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskName1)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetroceder)
                    .addComponent(btnAvancar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxConcluido)
                    .addComponent(taskName3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskName2)
                    .addComponent(txtDataDeCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newTaskWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrParaMenu)
                    .addComponent(btnExcluir)
                    .addComponent(btnGravar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newTaskWindow)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newTaskWindow)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnIrParaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrParaMenuActionPerformed
        fecharJanela();
    }//GEN-LAST:event_btnIrParaMenuActionPerformed

    private void checkBoxConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxConcluidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxConcluidoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
       int id = Integer.parseInt(txtId.getText());
        Tarefa tarefa = new Tarefa();
        tarefa.setNomeTarefa(txtNomeDaTarefa.getText());
        tarefa.setDescricao(txtDescricao.getText());
        tarefa.setConcluida(checkBoxConcluido.getText());
        tarefa.setDataCriacao(txtDataDeCriacao.getText());
        tarefa.setId(id);
        String mensagem;
            
        TarefaRepository tarefaRepository = new TarefaRepository();
        boolean retornoBanco = false;
        if (Integer.parseInt(txtId.getText()) == 0) {
            retornoBanco =  tarefaRepository.inserir(janelaPrincipal.conexaoMySQL.connection, pessoa);
            mensagem = "Tarefa inserido com sucesso!";
        } else {
          retornoBanco =  tarefaRepository.atualizar(janelaPrincipal.conexaoMySQL.connection, pessoa);
          mensagem = "Tarefa atualizada com sucesso!";
        } 

        if(retornoBanco) {
            JOptionPane.showMessageDialog(
                this,
                    mensagem,
                    "Tela de Cadastro",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limparJanela();
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void limparJanela(){
        txtNomeDaTarefa.setText("");
        txtDescricao.setText("");
        checkBoxConcluido.setText("");
        txtDataDeCriacao.setText("");
        txtNomeDaTarefa.requestFocus();
    }
    
    private void fecharJanela(){
        instancia = null;
        dispose();
    }
    
    public static JanelaNovaTarefa getInstancia(JanelaPrincipal janelaPrincipal){
        if(instancia == null)
            instancia = new JanelaNovaTarefa(janelaPrincipal);
        return instancia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIrParaMenu;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JCheckBox checkBoxConcluido;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JInternalFrame newTaskWindow;
    private javax.swing.JLabel taskName;
    private javax.swing.JLabel taskName1;
    private javax.swing.JLabel taskName2;
    private javax.swing.JLabel taskName3;
    private javax.swing.JTextField txtDataDeCriacao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeDaTarefa;
    // End of variables declaration//GEN-END:variables
}
